// Planet — renders a planet from a `cfg` (the config produced by
// the planet_editor and stored in zone planetMarkers).
//
// Faithful port of the legacy drawEditorPlanet() + helpers (lines
// ~1118-1308 of galaxtarus.html). Rendering covers : outer glow,
// body gradient (per type : gas, rocky, ice, lava, ocean, alien, dark),
// bands (gas/alien/dark), craters (rocky/ice), storms, clouds,
// atmosphere rim, shadow, specular highlight, rings (back + front),
// orbiting moons.

(function() {
  'use strict';

  // ── Config helpers ──────────────────────────────────────────────
  function _hex(hex) {
    if (!hex || hex.length < 7) return { r: 80, g: 80, b: 80 };
    return {
      r: parseInt(hex.slice(1, 3), 16),
      g: parseInt(hex.slice(3, 5), 16),
      b: parseInt(hex.slice(5, 7), 16),
    };
  }
  function _v(cfg, k, def = 0)  { return parseFloat(cfg[k] !== undefined ? cfg[k] : def); }
  function _i(cfg, k, def = 0)  { return parseInt(cfg[k] !== undefined ? cfg[k] : def); }
  function _c(cfg, k, def = '#404040') { return cfg[k] || def; }

  class Planet {
    /**
     * @param {string} name
     * @param {number} wx             - world x
     * @param {number} wy             - world y
     * @param {string} parallaxGroup  - registry layer id ('planets_far', 'planets_mid', …)
     *                                  Must be a string. Anything else triggers a warning
     *                                  and falls back to 'planets_far'.
     * @param {object} cfg            - planet config (from planet_editor)
     *
     * Note : data files generated by the legacy planet_editor still use
     * `parallaxFactor` (number 12 or 28). Those zones must be migrated to
     * `parallaxGroup` before loading. See NOTES_TECHNIQUES.md.
     */
    constructor(name, wx, wy, parallaxGroup, cfg, parallaxRegistry = null, fxRegistry = null) {
      this.name = name || 'Planet';
      this.wx = wx;
      this.wy = wy;
      this.cfg = cfg || {};
      // Optional parallax registry injection (règle 14). Falls back to the
      // legacy global GALAXTARUS.parallax when null.
      this._parallaxRegistry = parallaxRegistry;
      // Optional FX registry injection (règle 14). Falls back to the
      // legacy global GALAXTARUS.planetFx when null. The registry is
      // populated by content (e.g. assets/visuals/planet_fx/galaxtarus_planet_fx.js)
      // — the engine itself ships zero hardcoded planet FX.
      this._fxRegistry = fxRegistry;

      if (typeof parallaxGroup !== 'string') {
        console.warn(
          `[Planet] '${this.name}' missing or invalid parallaxGroup ` +
          `(got ${typeof parallaxGroup}). Falling back to 'planets_far'.`
        );
        this.parallaxGroup = 'planets_far';
      } else {
        this.parallaxGroup = parallaxGroup;
      }

      // Numeric fallback used by render() if the Parallax registry isn't loaded.
      // The actual value comes from GALAXTARUS.parallax.get(this.parallaxGroup).
      this.parallax = 0.12;
    }

    /**
     * Render the planet at its world position.
     * @param {CanvasRenderingContext2D} ctx
     * @param {{wx, wy, zoom}} camera
     * @param {number} t - global time in seconds
     */
    render(ctx, camera, t) {
      const W = ctx.canvas.width;
      const H = ctx.canvas.height;
      // Read parallax from registry at render time so the editor can adjust
      // it in live. Uses injection if present, fallback on legacy global.
      const reg = this._parallaxRegistry
                  || (window.GALAXTARUS && window.GALAXTARUS.parallax);
      const p = reg ? reg.get(this.parallaxGroup, this.parallax) : this.parallax;
      const zoom = camera.zoom;

      const sx = (this.wx - camera.wx) * p * zoom + W / 2;
      const sy = (this.wy - camera.wy) * p * zoom + H / 2;

      // Size : pRadius IS the radius the planet has at zoom = 1. Engine only
      // multiplies by camera.zoom — no hidden coefs, no parallax scaling.
      // Designer controls the size directly via pRadius. Predictable.
      // Position above keeps * p * zoom (parallax = movement, not size).
      const R = _v(this.cfg, 'pRadius', 60) * zoom;
      if (R < 2) return;

      const margin = 400;
      if (sx < -margin || sx > W + margin || sy < -margin || sy > H + margin) return;

      const fxReg = this._fxRegistry
                    || (window.GALAXTARUS && window.GALAXTARUS.planetFx);

      ctx.save();
      Planet._renderBody(ctx, this.cfg, sx, sy, R, t, fxReg);
      ctx.restore();
    }

    // ──────────────────────────────────────────────────────────────
    // INTERNAL : full planet rendering (body + atmosphere + rings + moons)
    // ──────────────────────────────────────────────────────────────
    static _renderBody(xctx, cfg, cx, cy, R, t, fxRegistry = null) {
      if (!cfg || R < 2) return;
      const type   = cfg.pType || 'gas';
      const col1   = _hex(_c(cfg, 'pCol1', '#4080C0'));
      const col2   = _hex(_c(cfg, 'pCol2', '#204060'));
      const col3   = _hex(_c(cfg, 'pCol3', '#306080'));
      const atmo   = _hex(_c(cfg, 'pAtmo', '#80C0FF'));
      const bands  = _i(cfg, 'pBands');
      const rotSpd = _v(cfg, 'pRot', 4) * 0.002;
      const turb   = _v(cfg, 'pTurb');
      const glowR  = _v(cfg, 'pGlow');
      const storms = _i(cfg, 'pStorm');
      const clouds = _v(cfg, 'pClouds');

      // Outer glow
      if (glowR > 0) {
        const grad = xctx.createRadialGradient(cx, cy, R * 0.9, cx, cy, R + glowR * 4);
        grad.addColorStop(0,   `rgba(${atmo.r},${atmo.g},${atmo.b},0.18)`);
        grad.addColorStop(0.5, `rgba(${atmo.r},${atmo.g},${atmo.b},0.06)`);
        grad.addColorStop(1,   'rgba(0,0,0,0)');
        xctx.fillStyle = grad;
        xctx.beginPath(); xctx.arc(cx, cy, R + glowR * 4, 0, Math.PI * 2); xctx.fill();
      }

      // Outside-BACK FX (rings far halves, moon orbits, halos that
      // go behind the body) — drawn before the body so the body covers
      // them where they overlap.
      if (fxRegistry) fxRegistry.renderAll(xctx, cfg, cx, cy, R, t, 'outside_back');

      // Back rings (engine) — far half of the ring, drawn before the body
      // so the body's clip will hide the part that overlaps the disc.
      Planet._renderRings(xctx, cfg, cx, cy, R, t, false);

      // Back moons — orbiting behind the planet (sin(ang) <= 0).
      // Drawn before the body so the body covers them where they overlap.
      Planet._renderMoons(xctx, cfg, cx, cy, R, t, false);

      // Body (clipped to circle)
      xctx.save();
      xctx.beginPath(); xctx.arc(cx, cy, R, 0, Math.PI * 2); xctx.clip();

      // Base gradient (per planet type)
      const bg = xctx.createRadialGradient(cx - R * 0.3, cy - R * 0.3, R * 0.05,
                                           cx + R * 0.1, cy + R * 0.1, R * 1.3);
      if (type === 'gas') {
        bg.addColorStop(0,   `rgb(${Math.min(255, col1.r + 50)},${Math.min(255, col1.g + 40)},${Math.min(255, col1.b + 30)})`);
        bg.addColorStop(0.5, `rgb(${col1.r},${col1.g},${col1.b})`);
        bg.addColorStop(1,   `rgb(${col2.r},${col2.g},${col2.b})`);
      } else if (type === 'rocky') {
        bg.addColorStop(0, `rgb(${Math.min(255, col1.r + 30)},${Math.min(255, col1.g + 30)},${Math.min(255, col1.b + 30)})`);
        bg.addColorStop(1, `rgb(${col2.r},${col2.g},${col2.b})`);
      } else if (type === 'ice') {
        bg.addColorStop(0,   '#E8F4FF');
        bg.addColorStop(0.6, '#90C8E0');
        bg.addColorStop(1,   '#3060A0');
      } else if (type === 'lava') {
        bg.addColorStop(0,   '#FF7020');
        bg.addColorStop(0.4, '#A03000');
        bg.addColorStop(1,   '#200800');
      } else if (type === 'ocean') {
        bg.addColorStop(0,   '#40B0E0');
        bg.addColorStop(0.5, '#1060A0');
        bg.addColorStop(1,   '#082040');
      } else if (type === 'alien') {
        bg.addColorStop(0,   `rgb(${col1.r},${Math.min(255, col1.g + 60)},${col1.b})`);
        bg.addColorStop(0.5, `rgb(${col2.r},${col2.g},${Math.min(255, col2.b + 80)})`);
        bg.addColorStop(1,   `rgb(${col3.r},${col3.g},${col3.b})`);
      } else if (type === 'dark') {
        bg.addColorStop(0,   '#1A0A30');
        bg.addColorStop(0.5, '#0A0518');
        bg.addColorStop(1,   '#020108');
      } else {
        bg.addColorStop(0, `rgb(${Math.min(255, col1.r + 40)},${Math.min(255, col1.g + 40)},${Math.min(255, col1.b + 40)})`);
        bg.addColorStop(1, `rgb(${col2.r},${col2.g},${col2.b})`);
      }
      xctx.fillStyle = bg;
      xctx.fillRect(cx - R, cy - R, R * 2, R * 2);

      // Bands (gas / alien / dark) — true continuous scroll.
      //
      // Each band has a permanent logical identity `i` (an integer that
      // can be negative). It moves down at a constant speed. We render
      // only the bands whose y-range crosses the planet's clipped circle.
      // No modulo, no per-frame reshuffling → no pop, ever.
      //
      // Math :
      //   y_i(t) = cy - R + (i + totalShift) * bandH
      //   Visible when : -1 ≤ (i + totalShift) ≤ bands + 1
      //                  ↔ -1 - totalShift ≤ i ≤ bands + 1 - totalShift
      if (bands > 0 && (type === 'gas' || type === 'alien' || type === 'dark')) {
        const bandH      = (R * 2) / bands;
        const totalShift = t * rotSpd * 50; // continuous, no modulo
        const minI       = Math.floor(-1 - totalShift);
        const maxI       = Math.ceil(bands + 1 - totalShift);
        for (let i = minI; i <= maxI; i++) {
          const by = cy - R + (i + totalShift) * bandH;
          if (by + bandH < cy - R - 1 || by > cy + R + 1) continue; // off-screen
          // i IS the logical index (permanent for that band's lifetime).
          const wave = turb > 0 ? Math.sin(t * 0.3 + i * 0.7) * turb * 2 : 0;
          const a    = 0.08 + Math.sin(i * 1.7) * 0.07;
          const mod3 = ((i % 3) + 3) % 3; // JS-safe positive modulo
          const bc   = mod3 === 0 ? col1 : (mod3 === 1 ? col2 : col3);
          xctx.fillStyle = `rgba(${bc.r},${bc.g},${bc.b},${Math.abs(a)})`;
          xctx.beginPath(); xctx.moveTo(cx - R, by + wave);
          for (let x = cx - R; x <= cx + R; x += 8) {
            const wv = turb > 0 ? Math.sin((x * 0.05) + t * 0.4 + i) * turb * 2 : 0;
            xctx.lineTo(x, by + wv);
          }
          xctx.lineTo(cx + R, by + bandH + wave);
          for (let x = cx + R; x >= cx - R; x -= 8) {
            const wv = turb > 0 ? Math.sin((x * 0.05) + t * 0.4 + i) * turb * 2 : 0;
            xctx.lineTo(x, by + bandH + wv);
          }
          xctx.closePath(); xctx.fill();
        }
      }

      // Craters (rocky / ice)
      if (type === 'rocky' || type === 'ice') {
        for (let i = 0; i < 14; i++) {
          const seed = i * 13.7;
          const cr   = R * (0.04 + Math.abs(Math.sin(seed)) * 0.08);
          const crx  = cx + Math.sin(seed * 4.3) * R * 0.85;
          const cry  = cy + Math.cos(seed * 2.7) * R * 0.85;
          if (Math.sqrt((crx - cx) ** 2 + (cry - cy) ** 2) + cr > R) continue;
          xctx.strokeStyle = 'rgba(0,0,0,0.2)';
          xctx.lineWidth   = 0.8;
          xctx.beginPath(); xctx.arc(crx, cry, cr, 0, Math.PI * 2); xctx.stroke();
          xctx.fillStyle = 'rgba(0,0,0,0.08)'; xctx.fill();
        }
        if (type === 'ice') {
          xctx.fillStyle = 'rgba(230,245,255,0.5)';
          xctx.beginPath();
          xctx.ellipse(cx, cy - R + R * 0.15, R * 0.5, R * 0.18, 0, 0, Math.PI * 2);
          xctx.fill();
        }
      }

      // Storms
      for (let s = 0; s < storms; s++) {
        const sx = cx + Math.cos(s * 1.4 + t * rotSpd * 20) * R * 0.5;
        const sy = cy + Math.sin(s * 2.1) * R * 0.3;
        const sr = R * 0.08 + Math.sin(t * 1.5 + s) * R * 0.02;
        xctx.save();
        xctx.translate(sx, sy);
        xctx.rotate(t * 0.5 + s);
        const sg = xctx.createRadialGradient(0, 0, 0, 0, 0, sr);
        const sc = s % 2 === 0 ? col1 : col3;
        sg.addColorStop(0,   `rgba(${sc.r},${sc.g},${sc.b},0.5)`);
        sg.addColorStop(0.6, `rgba(${sc.r},${sc.g},${sc.b},0.15)`);
        sg.addColorStop(1,   'rgba(0,0,0,0)');
        xctx.fillStyle = sg;
        xctx.beginPath(); xctx.ellipse(0, 0, sr * 1.6, sr, 0, 0, Math.PI * 2); xctx.fill();
        xctx.restore();
      }

      // Clouds (ocean / gas / rocky)
      if (clouds > 0 && (type === 'ocean' || type === 'gas' || type === 'rocky')) {
        for (let i = 0; i < clouds * 4; i++) {
          const ang = i / (clouds * 4) * Math.PI * 2 + t * rotSpd * 0.7;
          const cr  = R * (0.25 + Math.sin(i * 3.7) * 0.2);
          const cx2 = cx + Math.cos(ang) * cr;
          const cy2 = cy + Math.sin(ang) * cr * 0.6;
          if (Math.sqrt((cx2 - cx) ** 2 + (cy2 - cy) ** 2) > R * 0.93) continue;
          xctx.fillStyle = `rgba(255,255,255,${0.04 + Math.sin(i) * 0.03})`;
          xctx.beginPath();
          xctx.arc(cx2, cy2, R * 0.08 + Math.sin(i * 2.4) * R * 0.04, 0, Math.PI * 2);
          xctx.fill();
        }
      }

      // FX (game-specific decorations registered by content) — drawn
      // between the body and the atmosphere rim so they sit on the
      // surface but stay under the limb shading.
      if (fxRegistry) fxRegistry.renderAll(xctx, cfg, cx, cy, R, t, 'inside');

      // Atmosphere rim
      const rim = xctx.createRadialGradient(cx, cy, R * 0.72, cx, cy, R);
      rim.addColorStop(0,   'rgba(0,0,0,0)');
      rim.addColorStop(0.8, 'rgba(0,0,0,0)');
      rim.addColorStop(1,   `rgba(${atmo.r},${atmo.g},${atmo.b},0.45)`);
      xctx.fillStyle = rim;
      xctx.fillRect(cx - R, cy - R, R * 2, R * 2);

      // Shadow
      const shd = xctx.createRadialGradient(cx + R * 0.25, cy + R * 0.25, 0, cx, cy, R * 1.1);
      shd.addColorStop(0,    'rgba(0,0,0,0)');
      shd.addColorStop(0.45, 'rgba(0,0,0,0)');
      shd.addColorStop(1,    'rgba(0,0,15,0.6)');
      xctx.fillStyle = shd;
      xctx.fillRect(cx - R, cy - R, R * 2, R * 2);

      // Specular highlight
      const hl = xctx.createRadialGradient(cx - R * 0.38, cy - R * 0.38, 0,
                                           cx - R * 0.38, cy - R * 0.38, R * 0.65);
      hl.addColorStop(0, 'rgba(255,255,255,0.13)');
      hl.addColorStop(1, 'rgba(255,255,255,0)');
      xctx.fillStyle = hl;
      xctx.fillRect(cx - R, cy - R, R * 2, R * 2);

      xctx.restore();

      // Front moons — orbiting in front of the planet (sin(ang) > 0).
      // Drawn after the body so they sit on top, but before front rings so
      // those rings still cover them where they overlap.
      Planet._renderMoons(xctx, cfg, cx, cy, R, t, true);

      // Front rings (engine) — near half of the ring, drawn over the body.
      Planet._renderRings(xctx, cfg, cx, cy, R, t, true);

      // Outside-FRONT FX (rings near halves, moon craters, halos that go
      // over everything) — drawn last, no clip.
      if (fxRegistry) fxRegistry.renderAll(xctx, cfg, cx, cy, R, t, 'outside');
    }

    static _renderRings(xctx, cfg, cx, cy, R, t, front) {
      const rCount = _i(cfg, 'rCount');
      if (!rCount) return;
      // The engine ships only solid rings. Other types (dust/crystal/debris)
      // are FX content — let the registry render them in the 'outside' phase.
      const rType = cfg.rType;
      if (rType && rType !== 'solid') return;
      const thick  = _v(cfg, 'rThick', 14);
      const gap    = _v(cfg, 'rGap', 8);
      const tilt   = _v(cfg, 'rTilt', 22) * Math.PI / 180;
      const scaleY = Math.sin(tilt);
      const { r, g, b } = _hex(_c(cfg, 'rCol', '#C0905A'));
      const alpha  = _v(cfg, 'rAlpha', 60) / 100;

      xctx.save();
      xctx.translate(cx, cy);
      xctx.scale(1, scaleY);
      for (let ri = 0; ri < rCount; ri++) {
        const inner = R + gap * 1.5 + ri * (thick + gap);
        const ra    = alpha * (1 - ri * 0.12);
        const grad  = xctx.createRadialGradient(0, 0, inner, 0, 0, inner + thick);
        grad.addColorStop(0,    `rgba(${r},${g},${b},0)`);
        grad.addColorStop(0.15, `rgba(${r},${g},${b},${ra})`);
        grad.addColorStop(0.5,  `rgba(${Math.min(255, r + 35)},${Math.min(255, g + 25)},${Math.min(255, b + 10)},${ra})`);
        grad.addColorStop(0.85, `rgba(${r},${g},${b},${ra * 0.7})`);
        grad.addColorStop(1,    `rgba(${r},${g},${b},0)`);
        xctx.strokeStyle = grad;
        xctx.lineWidth   = thick;
        xctx.beginPath();
        // Inverted vs the legacy : in correct perspective, the FAR half
        // of the ring (top in screen-space when tilt > 0) is the "back"
        // and must be drawn before the body (so the body covers it where
        // they overlap). The NEAR half (bottom) is the "front".
        xctx.arc(0, 0, inner + thick / 2,
                 front ?  0       : -Math.PI,
                 front ?  Math.PI : 0);
        xctx.stroke();
      }
      xctx.restore();
    }

    static _renderMoons(xctx, cfg, cx, cy, R, t, front) {
      const mCount = _i(cfg, 'mCount');
      if (!mCount) return;
      const mSize  = _v(cfg, 'mSize', 6);
      const mDist  = _v(cfg, 'mDist', 90);
      const mSpd   = _v(cfg, 'mSpeed', 3) * 0.008;
      const mTilt  = _v(cfg, 'mTilt', 5) * Math.PI / 180;
      const { r, g, b } = _hex(_c(cfg, 'mCol', '#C0C0B0'));

      for (let i = 0; i < mCount; i++) {
        const ang     = t * mSpd * (1 - i * 0.12) + i * (Math.PI * 2 / mCount);
        // Front half (bottom in screen-space) = sin(ang) > 0. Skip the moons
        // that belong to the other half — caller renders this method twice,
        // once for back (before body) and once for front (after body). Mirror
        // pattern of _renderRings.
        const isFront = Math.sin(ang) > 0;
        if (isFront !== front) continue;
        const dist = mDist * (0.75 + i * 0.22);
        const mx   = cx + Math.cos(ang) * dist;
        const my   = cy + Math.sin(ang) * dist * Math.cos(mTilt + i * 0.15);
        const sz   = mSize * (1 - i * 0.08);

        // Moon body (lit side)
        const mg = xctx.createRadialGradient(mx - sz * 0.35, my - sz * 0.35, 0, mx, my, sz);
        mg.addColorStop(0, `rgba(${Math.min(255, r + 50)},${Math.min(255, g + 50)},${Math.min(255, b + 50)},1)`);
        mg.addColorStop(1, `rgba(${Math.floor(r * 0.4)},${Math.floor(g * 0.4)},${Math.floor(b * 0.4)},1)`);
        xctx.fillStyle = mg;
        xctx.beginPath(); xctx.arc(mx, my, sz, 0, Math.PI * 2); xctx.fill();

        // Moon shadow side
        const ms = xctx.createRadialGradient(mx + sz * 0.35, my + sz * 0.35, 0, mx, my, sz);
        ms.addColorStop(0, 'rgba(0,0,20,0.45)');
        ms.addColorStop(1, 'rgba(0,0,20,0)');
        xctx.fillStyle = ms;
        xctx.beginPath(); xctx.arc(mx, my, sz, 0, Math.PI * 2); xctx.fill();
      }
    }
  }

  // Expose on global namespace
  window.GALAXTARUS = window.GALAXTARUS || {};
  window.GALAXTARUS.Planet = Planet;
})();
